[settings]
agent_id = "bossdeboss/dominance-ppo"
name = "DominancePPO"
loadout_file = "loadout.toml"
run_command = "..\\..\\venv\\Scripts\\python bot.py"
run_command_linux = "../../venv/bin/python bot.py"

[details]
description = "PPO-trained neural network bot"
fun_fact = "Trained via reinforcement learning"
developer = "BossDeBoss"
language = "python"
tags = ["ml"]
