[blue_loadout]
team_color_id = 29
custom_color_id = 0
car_id = 23
decal_id = 0
wheels_id = 1580
boost_id = 35
antenna_id = 0
hat_id = 0
paint_finish_id = 0
custom_finish_id = 0
engine_audio_id = 0
trails_id = 3220
goal_explosion_id = 4118

[orange_loadout]
team_color_id = 69
custom_color_id = 0
car_id = 23
decal_id = 0
wheels_id = 1580
boost_id = 35
antenna_id = 0
hat_id = 0
paint_finish_id = 0
custom_finish_id = 0
engine_audio_id = 0
trails_id = 3220
goal_explosion_id = 4118
